nodes:
- chdir: true
  exec: gscam
  id: '0'
  inputs: []
  name: gscam
  outputs:
  - connections: ['1', '3']
    id: '0'
    name: image
    type: null
  params: []
  pkg: gscam
  remap: []
  x: 30
  y: 61
- chdir: false
  id: '1'
  inputs:
  - connections: ['0']
    id: '1'
    name: image
    type: null
  launch: cmvision.launch
  name: cmvision
  outputs:
  - connections: ['5']
    id: '2'
    name: blobs
    type: null
  params: []
  pkg: cmvision
  remap:
  - [image, /gscam/image_raw]
  x: 205
  y: 127
- chdir: true
  exec: ar_recog
  id: '2'
  inputs:
  - connections: ['0']
    id: '3'
    name: image
    type: null
  name: ar_recog
  outputs:
  - connections: ['7']
    id: '4'
    name: tags
    type: null
  params: []
  pkg: ar_recog
  remap:
  - [image, /gscam/image_raw]
  x: 275
  y: 30
- chdir: false
  id: '3'
  inputs:
  - connections: ['2']
    id: '5'
    name: blob_list
    type: null
  name: merge_blobs
  outputs:
  - connections: ['7']
    id: '6'
    name: blob_list
    type: null
  params: []
  pkg: ''
  remap: []
  x: 349
  y: 245
- chdir: false
  id: '4'
  inputs:
  - connections: ['6', '4']
    id: '7'
    name: blob_list
    type: null
  name: filter_blobs
  outputs:
  - connections: []
    id: '8'
    name: orange_over_green
    type: null
  - connections: ['14']
    id: '9'
    name: green_over_orange
    type: null
  - connections: []
    id: '10'
    name: orange
    type: null
  - connections: ['16']
    id: '11'
    name: green
    type: null
  - connections: []
    id: '12'
    name: yellow
    type: null
  - connections: []
    id: '13'
    name: pink
    type: null
  params: []
  pkg: ''
  remap: []
  x: 530
  y: 109
- chdir: false
  exec: seek_objects.py
  id: '5'
  inputs:
  - connections: ['9']
    id: '14'
    name: blob_list
    type: null
  name: seek_objects
  outputs:
  - connections: ['18']
    id: '15'
    name: twist
    type: null
  params: []
  pkg: ''
  remap: []
  x: 752
  y: 30
- chdir: false
  id: '6'
  inputs:
  - connections: ['11']
    id: '16'
    name: blob_list
    type: null
  name: avoid_objects
  outputs:
  - connections: ['18']
    id: '17'
    name: twist
    type: null
  params: []
  pkg: ''
  remap: []
  x: 779
  y: 213
- chdir: false
  exec: driver.py
  id: '7'
  inputs:
  - connections: ['15', '17']
    id: '18'
    name: twist
    type: null
  name: create_driver
  outputs: []
  params: []
  pkg: irobot_create_2_1
  remap: []
  x: 981
  y: 108
