nodes:
  - name: gscam
    x: 20
    y: 20
    id: 0
    inputs: []
    outputs:
      - type:
        id: 0
        name: image
        connections: [1, 3]
  - name: cmvision
    x: 20
    y: 20
    id: 1
    inputs:
      - type:
        id: 1
        name: image
    outputs:
      - type:
        id: 2
        name: blobs
        connections: [5]
  - name: ar_recog
    x: 20
    y: 20
    id: 2
    inputs:
      - type:
        id: 3
        name: image
    outputs:
      - type:
        id: 4
        name: tags
        connections: []
  - name: merge_blobs
    x: 20
    y: 20
    id: 3
    inputs:
      - type:
        id: 5
        name: blob_list
    outputs:
      - type:
        id: 6
        name: blob_list
        connections: [7]
  - name: filter_blobs
    x: 20
    y: 20
    id: 4
    inputs:
      - type:
        id: 7
        name: blob_list
    outputs:
      - type:
        id: 8
        name: orange_over_green
        connections: []
      - type:
        id: 9
        name: green_over_orange
        connections: [14]
      - type:
        id: 10
        name: orange
        connections: []
      - type:
        id: 11
        name: green
        connections: [16]
      - type:
        id: 12
        name: yellow
        connections: []
      - type:
        id: 13
        name: pink
        connections: []
  - name: seek_objects
    x: 20
    y: 20
    id: 5
    inputs:
      - type:
        id: 14
        name: blob_list
    outputs:
      - type:
        id: 15
        name: twist
        connections: [18]
  - name: avoid_objects
    x: 20
    y: 20
    id: 6
    inputs:
      - type:
        id: 16
        name: blob_list
    outputs:
      - type:
        id: 17
        name: twist
        connections: [18]
  - name: irobot_create_2_1
    x: 20
    y: 20
    id: 7
    inputs:
      - type:
        id: 18
        name: twist
    outputs: []
