nodes:
- chdir: false
  exec: send.py
  id: '1'
  inputs: []
  name: Sender
  outputs:
  - connections: ['2']
    id: '1'
    name: foo
    type: null
  params: []
  pkg: remapping_test
  remap: []
  x: 79
  y: 94
- chdir: false
  exec: recv.py
  id: '2'
  inputs:
  - connections: ['1']
    id: '2'
    name: bar
    type: null
  name: Receiver
  outputs: []
  params: []
  pkg: remapping_test
  remap: []
  x: 355
  y: 130
- chdir: false
  exec: send.py
  id: '3'
  inputs: []
  name: Sender
  outputs:
  - connections: ['4']
    id: '3'
    name: foo
    type: null
  params: []
  pkg: remapping_test
  remap: []
  x: 85
  y: 203
- chdir: false
  exec: recv.py
  id: '4'
  inputs:
  - connections: ['3']
    id: '4'
    name: bar
    type: null
  name: Receiver
  outputs: []
  params: []
  pkg: remapping_test
  remap: []
  x: 361
  y: 227
