nodes:
- chdir: false
  exec: driver.py
  id: '9100070830900222'
  inputs:
  - connections: [0622973358258605]
    id: 06748916977085173
    name: cmd_vel
    type: null
  name: iRobot Create Driver
  outputs:
  - connections: [011877913493663073]
    id: '973145708674565'
    name: sensorPacket
    type: null
  - connections: []
    id: '2182355155237019'
    name: odom
    type: null
  params:
  - {name: /brown/irobot_create_2_1/port, type: string, value: null}
  pkg: irobot_create_2_1
  remap: []
  x: 176
  y: 78
- chdir: false
  exec: line_follower.py
  id: '3382358932867646'
  inputs:
  - connections: ['973145708674565']
    id: 011877913493663073
    name: sensorPacket
    type: null
  name: iRobot Line Follower
  outputs:
  - connections: [06748916977085173]
    id: 0622973358258605
    name: cmd_vel
    type: null
  params: []
  pkg: line_follower
  remap: []
  x: 159
  y: 239
